### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by SilverScreamBr** [opentibiabr/tools#3]
Vocês tem os codigos-fonte do RME e do Item Editor assim como do Object Builder para me disponibilizar

**Comment by gpedro** [comment]
RME: http://github.com/hjnilsson/rme
ItemEditor: https://github.com/ottools/ItemEditor
Object Builder: https://github.com/ottools/ObjectBuilder

A maioria, se não todas, alterações realizadas nos arquivos, foram em arquivos externos (e não na source).
