### ISSUE TITLE
Link Client

### ISSUE THREAD

**Issue by augustorajas** [opentibiabr/tools#8]
Tem como vcs colocaram um link para o download separado do cliente 12.00?
.zip

**Comment by augustorajas** [comment]
@MajestyOTBR so isso fechar o Issue?

**Comment by MajestyOTBR** [comment]
Não vamos colocar link de download separado (.zip) toda vez que o cliente 12 for atualizado.

Respondido.

**Comment by MajestyOTBR** [comment]
Entre no Discord:
https://discord.gg/3NxYnyV
